'use strict';

exports.CACHE_COVER = 'CACHE_COVER';
exports.CACHE_UPDATE = 'CACHE_UPDATE';
exports.CACHE_PUSH = 'CACHE_PUSH';
exports.CACHE_CLEAR = 'CACHE_CLEAR';
exports.CACHE_UPDATE_BY_KEY = 'CACHE_UPDATE_BY_KEY';

exports.WORKER_READY = 'WORKER_READY';
exports.ALL_WORKER_READY = 'ALL_WORKER_READY';
